In [0]:
#IMPORTING IMPORTANT LIBRARIES
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import k_means

In [0]:
#READING THE GIVEN DATASET
#NAMING THE DATASET AS dataset
df = pd.read_csv('dataset.csv')

In [0]:
df

Customer       State  ...  Vehicle Class Vehicle Size
0     BU79786  Washington  ...   Two-Door Car      Medsize
1     QZ44356     Arizona  ...  Four-Door Car      Medsize
2     AI49188      Nevada  ...   Two-Door Car      Medsize
3     WW63253  California  ...            SUV      Medsize
4     HB64268  Washington  ...  Four-Door Car      Medsize
...       ...         ...  ...            ...          ...
8289  TQ82322  California  ...   Two-Door Car      Medsize
8290  CB77819  California  ...   Two-Door Car      Medsize
8291  VG68427     Arizona  ...  Four-Door Car      Medsize
8292  WO42164      Oregon  ...  Four-Door Car      Medsize
8293  NL87371      Oregon  ...            NaN          NaN

[8294 rows x 24 columns]

In [0]:
#SHAPE OF THE DATASET
print(df.shape)

(8294, 24)


In [0]:
print(df.columns)

Index(['Customer', 'State', 'Customer Lifetime Value', 'Response', 'Coverage',
       'Education', 'Effective To Date', 'EmploymentStatus', 'Gender',
       'Income', 'Location Code', 'Marital Status', 'Monthly Premium Auto',
       'Months Since Last Claim', 'Months Since Policy Inception',
       'Number of Open Complaints', 'Number of Policies', 'Policy Type',
       'Policy', 'Renew Offer Type', 'Sales Channel', 'Total Claim Amount',
       'Vehicle Class', 'Vehicle Size'],
      dtype='object')


In [0]:
df["Customer"].value_counts()

AH58807    1
WV76014    1
OY92520    1
ZZ44902    1
BZ71120    1
          ..
AN79079    1
EP61197    1
AY35539    1
DS50601    1
WI69346    1
Name: Customer, Length: 8294, dtype: int64

In [0]:
df["Effective To Date"].value_counts()

01/10/11    178
1/27/11     177
1/31/11     168
2/14/11     167
1/17/11     165
1/19/11     164
01/03/11    163
01/05/11    157
1/26/11     157
2/27/11     157
1/20/11     154
2/19/11     153
2/28/11     152
1/28/11     152
02/04/11    151
2/26/11     150
1/29/11     149
01/11/11    147
02/05/11    146
02/03/11    146
1/18/11     145
01/02/11    145
1/21/11     144
2/22/11     144
1/15/11     143
02/10/11    143
02/07/11    142
02/01/11    142
1/23/11     141
1/14/11     139
2/18/11     137
02/12/11    137
01/07/11    137
1/25/11     137
1/13/11     136
01/01/11    136
01/08/11    135
2/25/11     134
02/02/11    134
02/11/11    134
2/21/11     133
1/30/11     131
1/24/11     130
2/13/11     130
01/09/11    130
1/16/11     129
01/06/11    127
2/23/11     127
2/24/11     126
1/22/11     125
02/06/11    125
02/08/11    125
02/09/11    123
2/17/11     122
2/15/11     120
2/16/11     117
2/20/11     116
01/12/11    115
01/04/11    104
1/            1
Name: Effective To Date, dtype: int64

In [0]:
#REMOVING MISSING VALUES
df =df.dropna()

In [0]:
#MAKING A COPY OF THE OBJECT'S INDICES AND DATA.
X1= df.copy()

In [0]:
del X1['Customer']

In [0]:
del X1['Effective To Date']

In [0]:
X4=pd.get_dummies(X1)

In [0]:
n=10

In [0]:
clf=k_means(X4,n_clusters=n)

In [0]:
clf

(array([[ 2.92345630e+04,  3.12768692e+04,  1.25331776e+02,
          1.63224299e+01,  5.14065421e+01,  2.66355140e-01,
          2.22897196e+00,  5.76773121e+02,  2.33644860e-01,
          2.57009346e-01,  1.16822430e-01,  3.08411215e-01,
          8.41121495e-02,  8.13084112e-01,  1.86915888e-01,
          4.48598131e-01,  3.87850467e-01,  1.63551402e-01,
          2.99065421e-01,  1.86915888e-01,  4.67289720e-02,
          3.64485981e-01,  1.02803738e-01,  8.41121495e-02,
          7.80373832e-01,  9.34579439e-02,  4.20560748e-02,
          9.99200722e-16,  6.02803738e-01,  3.97196262e-01,
          1.63551402e-01,  6.44859813e-01,  1.91588785e-01,
          1.86915888e-01,  6.30841121e-01,  1.82242991e-01,
          1.54205607e-01,  7.89719626e-01,  5.60747664e-02,
          3.73831776e-02,  3.27102804e-02,  8.41121495e-02,
          1.12149533e-01,  2.80373832e-01,  3.97196262e-01,
          4.67289720e-03,  2.33644860e-02,  2.80373832e-02,
          4.95327103e-01,  2.99065421e-0

In [0]:
centroids=clf[0]

In [0]:
labels=clf[1]

In [0]:
centroids

array([[ 2.92345630e+04,  3.12768692e+04,  1.25331776e+02,
         1.63224299e+01,  5.14065421e+01,  2.66355140e-01,
         2.22897196e+00,  5.76773121e+02,  2.33644860e-01,
         2.57009346e-01,  1.16822430e-01,  3.08411215e-01,
         8.41121495e-02,  8.13084112e-01,  1.86915888e-01,
         4.48598131e-01,  3.87850467e-01,  1.63551402e-01,
         2.99065421e-01,  1.86915888e-01,  4.67289720e-02,
         3.64485981e-01,  1.02803738e-01,  8.41121495e-02,
         7.80373832e-01,  9.34579439e-02,  4.20560748e-02,
         9.99200722e-16,  6.02803738e-01,  3.97196262e-01,
         1.63551402e-01,  6.44859813e-01,  1.91588785e-01,
         1.86915888e-01,  6.30841121e-01,  1.82242991e-01,
         1.54205607e-01,  7.89719626e-01,  5.60747664e-02,
         3.73831776e-02,  3.27102804e-02,  8.41121495e-02,
         1.12149533e-01,  2.80373832e-01,  3.97196262e-01,
         4.67289720e-03,  2.33644860e-02,  2.80373832e-02,
         4.95327103e-01,  2.99065421e-01,  1.26168224e-0

In [0]:
labels

array([3, 2, 8, ..., 2, 1, 2], dtype=int32)

In [0]:
#Computing the Davies-Bouldin score.
#The score is defined as the average similarity measure of each cluster with its most similar cluster, where similarity is the ratio of within-cluster distances to between-cluster distances. Thus, clusters which are farther apart and less dispersed will result in a better score.
#Here the minimum score is zero, with lower values indicating better clustering.
import sklearn as sklearn
sklearn.metrics.davies_bouldin_score(X4, labels)

0.7219023984956315